### ISSUE TITLE
'toggle_percent' command previously bound

### ISSUE THREAD

**Issue by Paradiesstaub** [zcoder/mocp#4]
Version: 2.5.0
OS: Ubuntu 15.10 Ubuntu (development branch)

What I would like to do:
I would like to set CTRL+n and CTRL+p to `menu_down` and `menu_up` in the `.moc/keymap` file (emacs like navigation). This works for CTRL+n, but not for CTRL+p.

Problem:
When setting `menu_up = UP ^p` I get the error:  
`FATAL_ERROR: Key ^p is defined for menu_up and toggle_percent!`

I haven't set `toggle_percent` nor did I found an entry in any of moc's config files. Setting `toggle_percent` in the keymap file results in `command previously bound` error.

**Comment by ethan626** [comment]
@Paradiesstaub 
I just set menu_up/menu_down to ctrl+n/p with no errors. Maybe toggle_percent is set by default in your version, it's at the bottom of the config, or you could try rebinding it to something else?

**Comment by thibran** [comment]
It's too long ago, can't really remember. `ctrl+n/p` works now for me, but I have no clue if and when I changed something. I guess the bug report can be closed.

**Comment by ethan626** [comment]
Well @zcoder can close it
